module.exports = {
    "env": {
        "browser": true,
        "es6": true,
        "node": true
    },
    "globals": {
        // elm runtime
        "F2": false,
        "F3": false,
        "F4": false,
        "F5": false,
        "F6": false,
        "F7": false,
        "F8": false,
        "F9": false,
        "A2": false,
        "A3": false,
        "A4": false,
        "A5": false,
        "A6": false,
        "A7": false,
        "A8": false,
        "A9": false,
        // elm-lang/core
        // native modules
        "_elm_lang$core$Native_Array": false,
        "_elm_lang$core$Native_Basics": false,
        "_elm_lang$core$Native_Bitwise": false,
        "_elm_lang$core$Native_Char": false,
        "_elm_lang$core$Native_Date": false,
        "_elm_lang$core$Native_Debug": false,
        "_elm_lang$core$Native_Json": false,
        "_elm_lang$core$Native_List": false,
        "_elm_lang$core$Native_Platform": false,
        "_elm_lang$core$Native_Regex": false,
        "_elm_lang$core$Native_Scheduler": false,
        "_elm_lang$core$Native_String": false,
        "_elm_lang$core$Native_Time": false,
        "_elm_lang$core$Native_Utils": false,
        // modules
        "_elm_lang$core$Result$Ok": false,
        "_elm_lang$core$Result$Err": false,
        "_elm_lang$core$Maybe$Just": false,
        "_elm_lang$core$Maybe$Nothing": false
    },
    "extends": "eslint:recommended",
    "rules": {
        // Conventions
        "default-case" : "error",
        "eqeqeq" : "error",
        "no-console": ["error", {allow: ["warn", "error"]}],
        "no-else-return" : "error",
        "no-lone-blocks" : "error",
        "no-shadow": "error",
        "no-shadow-restricted-names": "error",
        "no-unexpected-multiline" : "error",
        "no-unused-vars": "off",
        "no-use-before-define": "error",
        // Format
        "comma-style" : ["error", "first"],
        "curly" : ["error", "multi-or-nest", "consistent"],
        "dot-notation" : "error",
        "no-extra-parens": "error",
        "no-underscore-dangle": "off",
        "nonblock-statement-body-position" : ["error", "beside"],
        "one-var" : ["error", "never"],
        "one-var-declaration-per-line" : ["error", "always"],
        "quotes": [ "error", "double", {"allowTemplateLiterals": true } ],
        "semi": [ "error", "never" ],
        // spacing
        "array-bracket-spacing": ["error", "always"],
        "arrow-spacing" : ["error", {"before": true, "after": true}],
        "indent": [ "error", 4 ],
        "comma-spacing" : ["error", {"before": false, "after": true}],
        "func-call-spacing": ["error", "never"],
        "key-spacing" : ["error", {"beforeColon": true, "afterColon": true, "mode": "strict"}],
        "keyword-spacing": ["error", {"before": true, "after": true}],
        "no-trailing-spaces": "error",
        "object-curly-spacing": ["error", "always"],
        "semi-spacing": ["error", {"before": false, "after": true}],
        "space-before-blocks": ["error", "always"],
        "space-before-function-paren": ["error", "always"],
        "spaced-comment": ["error", "always"],
        "space-infix-ops": "error",
        // lines
        "eol-last": "error",
        "linebreak-style": [ "error", "unix" ],
        // "object-curly-newline" : ["error", "never"],
        "padded-blocks": ["error", "never"],
        "no-multiple-empty-lines": ["error", {"max" : 2, "maxEOF": 1, "maxBOF": 0 }]
    }
};
